name: CI/CD ASP.NET Core Web App

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Análisis estático con SonarCloud (Windows CLI)
      shell: pwsh
      run: |
        "C:\Users\justi\OneDrive\Escritorio\sonar-scanner-7.1.0.4889-windows-x64\bin\sonar-scanner.bat" `
          -Dsonar.projectKey=jhonpaul12_Aplicacion_Web_GA `
          -Dsonar.organization=jhonpaul12 `
          -Dsonar.host.url=https://sonarcloud.io `
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Compilar
      run: dotnet build --configuration Release --no-restore

    - name: Ejecutar pruebas
      run: dotnet test --no-build

    - name: Publicar
      run: dotnet publish -c Release -o ./publish

    - name: Desplegar en IIS con PowerShell
      shell: pwsh
      run: ./deploy.ps1 -publishFolder ./publish -iisFolder "C:\\inetpub\\wwwroot\\MiApp"

