name: CI/CD ASP.NET Core Web App

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar
      run: dotnet build --configuration Release --no-restore

    - name: Ejecutar pruebas
      run: dotnet test --no-build

    - name: Publicar
      run: dotnet publish -c Release -o ./publish

    - name: Desplegar en IIS con PowerShell
      shell: pwsh
      run: ./deploy.ps1 -publishFolder ./publish -iisFolder "C:\\inetpub\\wwwroot\\MiApp"
