name: CI/CD ASP.NET Core Web App

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Análisis estático con SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      with:
        organization: JhonPaul12  # remplaza con el ID exacto de tu organización en SonarCloud
        projectKey: JhonPaul12_Aplicacion_Web_GA  # remplaza con el projectKey exacto que creaste
        projectName: Aplicacion_Web_GA
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Compilar
      run: dotnet build --configuration Release --no-restore

    - name: Ejecutar pruebas
      run: dotnet test --no-build

    - name: Publicar
      run: dotnet publish -c Release -o ./publish

    - name: Desplegar en IIS con PowerShell
      shell: pwsh
      run: ./deploy.ps1 -publishFolder ./publish -iisFolder "C:\\inetpub\\wwwroot\\MiApp"
