name: CI/CD ASP.NET Core Web App

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Análisis estático con SonarCloud
      uses: SonarSource/sonarqube-scan-action@v2.0.0
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_PROJECT_KEY: jhonpaul12_Aplicacion_Web_GA
        SONAR_ORGANIZATION: jhonpaul12


    - name: Compilar
      run: dotnet build --configuration Release --no-restore

    - name: Ejecutar pruebas
      run: dotnet test --no-build

    - name: Publicar
      run: dotnet publish -c Release -o ./publish

    - name: Desplegar en IIS con PowerShell
      shell: pwsh
      run: ./deploy.ps1 -publishFolder ./publish -iisFolder "C:\\inetpub\\wwwroot\\MiApp"
